stages:
- build

build-all:
  stage: build
  image: docker:19.03@sha256:b8a8caa37f283d18ca5a5066b7b79c95b401327061381df950712a585030043c
  script:
  - mkdir .docker
  - export DOCKER_CERT_PATH=$(pwd)/.docker
  - export DOCKER_HOST=tcp://docker-amd64:2376
  - echo "${PROJ_CI_DOCKER_CA_CERT:?please set variable in Gitlab CI settings}" > .docker/ca.pem
  - echo "${PROJ_CI_DOCKER_CLIENT_CERT:?please set variable in Gitlab CI settings}" > .docker/cert.pem
  - echo "${PROJ_CI_DOCKER_CLIENT_KEY:?please set variable in Gitlab CI settings}" > .docker/key.pem
  - docker version

